### ISSUE TITLE
Consider adding an RSS/Atom feed

### ISSUE THREAD

**Issue by eudoxia0** [slightknack/slightknack.dev#6]
This may be useful to other readers like me who want to subscribe.

**Comment by slightknack** [comment]
Love your work on Austral man! There is a feed at [`https://slightknack.dev/atom.xml`](https://slightknack.dev/atom.xml), I've added a more visible link.

<img width="900" alt="Screenshot 2024-12-26 at 8 06 36 AM" src="https://github.com/user-attachments/assets/56e316ad-0524-4b1f-9f42-4d8dc67509ae" />

**Comment by eudoxia0** [comment]
> Love your work on Austral man!

Thanks!

> There is a feed at https://slightknack.dev/atom.xml, I've added a more visible link.

Oh weird. I think I couldn't find it since there's no `<link>` tag that points to the feed, and I tried `/feed.xml` but that obviously was the wrong file name.

**Comment by slightknack** [comment]
> I think I couldn't find it since there's no <link> tag

Oh, good catch! Let me add that ...

As an aside, I'd love to chat with you sometime about Austral! Send me an email (hi@isaac.sh) with your preferred means of communication (WhatsApp, Matrix, Discord) and I'll send you a message :)
